import 'libc.dart';

int get ACCESSPERMS => libc.ACCESSPERMS;
int get ALLPERMS => libc.ALLPERMS;
int get AT_EACCESS => libc.AT_EACCESS;
int get AT_FDCWD => libc.AT_FDCWD;
int get AT_REMOVEDIR => libc.AT_REMOVEDIR;
int get AT_SYMLINK_FOLLOW => libc.AT_SYMLINK_FOLLOW;
int get AT_SYMLINK_NOFOLLOW => libc.AT_SYMLINK_NOFOLLOW;
int get BIG_ENDIAN => libc.BIG_ENDIAN;
int get BYTE_ORDER => libc.BYTE_ORDER;
int get DEFFILEMODE => libc.DEFFILEMODE;
int get E2BIG => libc.E2BIG;
int get EACCES => libc.EACCES;
int get EADDRINUSE => libc.EADDRINUSE;
int get EADDRNOTAVAIL => libc.EADDRNOTAVAIL;
int get EADV => libc.EADV;
int get EAFNOSUPPORT => libc.EAFNOSUPPORT;
int get EAGAIN => libc.EAGAIN;
int get EALREADY => libc.EALREADY;
int get EBADE => libc.EBADE;
int get EBADF => libc.EBADF;
int get EBADFD => libc.EBADFD;
int get EBADMSG => libc.EBADMSG;
int get EBADR => libc.EBADR;
int get EBADRQC => libc.EBADRQC;
int get EBADSLT => libc.EBADSLT;
int get EBFONT => libc.EBFONT;
int get EBUSY => libc.EBUSY;
int get ECANCELED => libc.ECANCELED;
int get ECHILD => libc.ECHILD;
int get ECHRNG => libc.ECHRNG;
int get ECOMM => libc.ECOMM;
int get ECONNABORTED => libc.ECONNABORTED;
int get ECONNREFUSED => libc.ECONNREFUSED;
int get ECONNRESET => libc.ECONNRESET;
int get EDEADLK => libc.EDEADLK;
int get EDEADLOCK => libc.EDEADLOCK;
int get EDESTADDRREQ => libc.EDESTADDRREQ;
int get EDOM => libc.EDOM;
int get EDOTDOT => libc.EDOTDOT;
int get EDQUOT => libc.EDQUOT;
int get EEXIST => libc.EEXIST;
int get EFAULT => libc.EFAULT;
int get EFBIG => libc.EFBIG;
int get EHOSTDOWN => libc.EHOSTDOWN;
int get EHOSTUNREACH => libc.EHOSTUNREACH;
int get EHWPOISON => libc.EHWPOISON;
int get EIDRM => libc.EIDRM;
int get EILSEQ => libc.EILSEQ;
int get EINPROGRESS => libc.EINPROGRESS;
int get EINTR => libc.EINTR;
int get EINVAL => libc.EINVAL;
int get EIO => libc.EIO;
int get EISCONN => libc.EISCONN;
int get EISDIR => libc.EISDIR;
int get EISNAM => libc.EISNAM;
int get EKEYEXPIRED => libc.EKEYEXPIRED;
int get EKEYREJECTED => libc.EKEYREJECTED;
int get EKEYREVOKED => libc.EKEYREVOKED;
int get EL2HLT => libc.EL2HLT;
int get EL2NSYNC => libc.EL2NSYNC;
int get EL3HLT => libc.EL3HLT;
int get EL3RST => libc.EL3RST;
int get ELIBACC => libc.ELIBACC;
int get ELIBBAD => libc.ELIBBAD;
int get ELIBEXEC => libc.ELIBEXEC;
int get ELIBMAX => libc.ELIBMAX;
int get ELIBSCN => libc.ELIBSCN;
int get ELNRNG => libc.ELNRNG;
int get ELOOP => libc.ELOOP;
int get EMEDIUMTYPE => libc.EMEDIUMTYPE;
int get EMFILE => libc.EMFILE;
int get EMLINK => libc.EMLINK;
int get EMSGSIZE => libc.EMSGSIZE;
int get EMULTIHOP => libc.EMULTIHOP;
int get ENAMETOOLONG => libc.ENAMETOOLONG;
int get ENAVAIL => libc.ENAVAIL;
int get ENETDOWN => libc.ENETDOWN;
int get ENETRESET => libc.ENETRESET;
int get ENETUNREACH => libc.ENETUNREACH;
int get ENFILE => libc.ENFILE;
int get ENOANO => libc.ENOANO;
int get ENOBUFS => libc.ENOBUFS;
int get ENOCSI => libc.ENOCSI;
int get ENODATA => libc.ENODATA;
int get ENODEV => libc.ENODEV;
int get ENOENT => libc.ENOENT;
int get ENOEXEC => libc.ENOEXEC;
int get ENOKEY => libc.ENOKEY;
int get ENOLCK => libc.ENOLCK;
int get ENOLINK => libc.ENOLINK;
int get ENOMEDIUM => libc.ENOMEDIUM;
int get ENOMEM => libc.ENOMEM;
int get ENOMSG => libc.ENOMSG;
int get ENONET => libc.ENONET;
int get ENOPKG => libc.ENOPKG;
int get ENOPROTOOPT => libc.ENOPROTOOPT;
int get ENOSPC => libc.ENOSPC;
int get ENOSR => libc.ENOSR;
int get ENOSTR => libc.ENOSTR;
int get ENOSYS => libc.ENOSYS;
int get ENOTBLK => libc.ENOTBLK;
int get ENOTCONN => libc.ENOTCONN;
int get ENOTDIR => libc.ENOTDIR;
int get ENOTEMPTY => libc.ENOTEMPTY;
int get ENOTNAM => libc.ENOTNAM;
int get ENOTRECOVERABLE => libc.ENOTRECOVERABLE;
int get ENOTSOCK => libc.ENOTSOCK;
int get ENOTSUP => libc.ENOTSUP;
int get ENOTTY => libc.ENOTTY;
int get ENOTUNIQ => libc.ENOTUNIQ;
int get ENXIO => libc.ENXIO;
int get EOPNOTSUPP => libc.EOPNOTSUPP;
int get EOVERFLOW => libc.EOVERFLOW;
int get EOWNERDEAD => libc.EOWNERDEAD;
int get EPERM => libc.EPERM;
int get EPFNOSUPPORT => libc.EPFNOSUPPORT;
int get EPIPE => libc.EPIPE;
int get EPROTO => libc.EPROTO;
int get EPROTONOSUPPORT => libc.EPROTONOSUPPORT;
int get EPROTOTYPE => libc.EPROTOTYPE;
int get ERANGE => libc.ERANGE;
int get EREMCHG => libc.EREMCHG;
int get EREMOTE => libc.EREMOTE;
int get EREMOTEIO => libc.EREMOTEIO;
int get ERESTART => libc.ERESTART;
int get ERFKILL => libc.ERFKILL;
int get EROFS => libc.EROFS;
int get ESHUTDOWN => libc.ESHUTDOWN;
int get ESOCKTNOSUPPORT => libc.ESOCKTNOSUPPORT;
int get ESPIPE => libc.ESPIPE;
int get ESRCH => libc.ESRCH;
int get ESRMNT => libc.ESRMNT;
int get ESTALE => libc.ESTALE;
int get ESTRPIPE => libc.ESTRPIPE;
int get ETIME => libc.ETIME;
int get ETIMEDOUT => libc.ETIMEDOUT;
int get ETOOMANYREFS => libc.ETOOMANYREFS;
int get ETXTBSY => libc.ETXTBSY;
int get EUCLEAN => libc.EUCLEAN;
int get EUNATCH => libc.EUNATCH;
int get EUSERS => libc.EUSERS;
int get EWOULDBLOCK => libc.EWOULDBLOCK;
int get EXDEV => libc.EXDEV;
int get EXFULL => libc.EXFULL;
int get EXIT_FAILURE => libc.EXIT_FAILURE;
int get EXIT_SUCCESS => libc.EXIT_SUCCESS;
int get FAPPEND => libc.FAPPEND;
int get FASYNC => libc.FASYNC;
int get FD_CLOEXEC => libc.FD_CLOEXEC;
int get FD_SETSIZE => libc.FD_SETSIZE;
int get FFSYNC => libc.FFSYNC;
int get FNDELAY => libc.FNDELAY;
int get FNM_CASEFOLD => libc.FNM_CASEFOLD;
int get FNM_EXTMATCH => libc.FNM_EXTMATCH;
int get FNM_FILE_NAME => libc.FNM_FILE_NAME;
int get FNM_LEADING_DIR => libc.FNM_LEADING_DIR;
int get FNM_NOESCAPE => libc.FNM_NOESCAPE;
int get FNM_NOMATCH => libc.FNM_NOMATCH;
int get FNM_PATHNAME => libc.FNM_PATHNAME;
int get FNM_PERIOD => libc.FNM_PERIOD;
int get FNONBLOCK => libc.FNONBLOCK;
int get F_DUPFD => libc.F_DUPFD;
int get F_DUPFD_CLOEXEC => libc.F_DUPFD_CLOEXEC;
int get F_EXLCK => libc.F_EXLCK;
int get F_GETFD => libc.F_GETFD;
int get F_GETFL => libc.F_GETFL;
int get F_GETLK => libc.F_GETLK;
int get F_GETLK64 => libc.F_GETLK64;
int get F_GETOWN => libc.F_GETOWN;
int get F_LOCK => libc.F_LOCK;
int get F_OK => libc.F_OK;
int get F_RDLCK => libc.F_RDLCK;
int get F_SETFD => libc.F_SETFD;
int get F_SETFL => libc.F_SETFL;
int get F_SETLK => libc.F_SETLK;
int get F_SETLK64 => libc.F_SETLK64;
int get F_SETLKW => libc.F_SETLKW;
int get F_SETLKW64 => libc.F_SETLKW64;
int get F_SETOWN => libc.F_SETOWN;
int get F_SHLCK => libc.F_SHLCK;
int get F_TEST => libc.F_TEST;
int get F_TLOCK => libc.F_TLOCK;
int get F_ULOCK => libc.F_ULOCK;
int get F_UNLCK => libc.F_UNLCK;
int get F_WRLCK => libc.F_WRLCK;
int get GLOB_ABORTED => libc.GLOB_ABORTED;
int get GLOB_ALTDIRFUNC => libc.GLOB_ALTDIRFUNC;
int get GLOB_APPEND => libc.GLOB_APPEND;
int get GLOB_BRACE => libc.GLOB_BRACE;
int get GLOB_DOOFFS => libc.GLOB_DOOFFS;
int get GLOB_ERR => libc.GLOB_ERR;
int get GLOB_MAGCHAR => libc.GLOB_MAGCHAR;
int get GLOB_MARK => libc.GLOB_MARK;
int get GLOB_NOCHECK => libc.GLOB_NOCHECK;
int get GLOB_NOESCAPE => libc.GLOB_NOESCAPE;
int get GLOB_NOMAGIC => libc.GLOB_NOMAGIC;
int get GLOB_NOMATCH => libc.GLOB_NOMATCH;
int get GLOB_NOSORT => libc.GLOB_NOSORT;
int get GLOB_NOSPACE => libc.GLOB_NOSPACE;
int get GLOB_NOSYS => libc.GLOB_NOSYS;
int get GLOB_ONLYDIR => libc.GLOB_ONLYDIR;
int get GLOB_PERIOD => libc.GLOB_PERIOD;
int get GLOB_TILDE => libc.GLOB_TILDE;
int get GLOB_TILDE_CHECK => libc.GLOB_TILDE_CHECK;
int get LITTLE_ENDIAN => libc.LITTLE_ENDIAN;
int get LOCK_EX => libc.LOCK_EX;
int get LOCK_NB => libc.LOCK_NB;
int get LOCK_SH => libc.LOCK_SH;
int get LOCK_UN => libc.LOCK_UN;
int get LOG_ALERT => libc.LOG_ALERT;
int get LOG_AUTH => libc.LOG_AUTH;
int get LOG_AUTHPRIV => libc.LOG_AUTHPRIV;
int get LOG_CONS => libc.LOG_CONS;
int get LOG_CRIT => libc.LOG_CRIT;
int get LOG_CRON => libc.LOG_CRON;
int get LOG_DAEMON => libc.LOG_DAEMON;
int get LOG_DEBUG => libc.LOG_DEBUG;
int get LOG_EMERG => libc.LOG_EMERG;
int get LOG_ERR => libc.LOG_ERR;
int get LOG_FACMASK => libc.LOG_FACMASK;
int get LOG_FTP => libc.LOG_FTP;
int get LOG_INFO => libc.LOG_INFO;
int get LOG_KERN => libc.LOG_KERN;
int get LOG_LOCAL0 => libc.LOG_LOCAL0;
int get LOG_LOCAL1 => libc.LOG_LOCAL1;
int get LOG_LOCAL2 => libc.LOG_LOCAL2;
int get LOG_LOCAL3 => libc.LOG_LOCAL3;
int get LOG_LOCAL4 => libc.LOG_LOCAL4;
int get LOG_LOCAL5 => libc.LOG_LOCAL5;
int get LOG_LOCAL6 => libc.LOG_LOCAL6;
int get LOG_LOCAL7 => libc.LOG_LOCAL7;
int get LOG_LPR => libc.LOG_LPR;
int get LOG_MAIL => libc.LOG_MAIL;
int get LOG_NDELAY => libc.LOG_NDELAY;
int get LOG_NEWS => libc.LOG_NEWS;
int get LOG_NFACILITIES => libc.LOG_NFACILITIES;
int get LOG_NOTICE => libc.LOG_NOTICE;
int get LOG_NOWAIT => libc.LOG_NOWAIT;
int get LOG_ODELAY => libc.LOG_ODELAY;
int get LOG_PERROR => libc.LOG_PERROR;
int get LOG_PID => libc.LOG_PID;
int get LOG_PRIMASK => libc.LOG_PRIMASK;
int get LOG_SYSLOG => libc.LOG_SYSLOG;
int get LOG_USER => libc.LOG_USER;
int get LOG_UUCP => libc.LOG_UUCP;
int get LOG_WARNING => libc.LOG_WARNING;
int get L_INCR => libc.L_INCR;
int get L_SET => libc.L_SET;
int get L_XTND => libc.L_XTND;
int get MADV_DODUMP => libc.MADV_DODUMP;
int get MADV_DOFORK => libc.MADV_DOFORK;
int get MADV_DONTDUMP => libc.MADV_DONTDUMP;
int get MADV_DONTFORK => libc.MADV_DONTFORK;
int get MADV_DONTNEED => libc.MADV_DONTNEED;
int get MADV_FREE => libc.MADV_FREE;
int get MADV_HUGEPAGE => libc.MADV_HUGEPAGE;
int get MADV_HWPOISON => libc.MADV_HWPOISON;
int get MADV_KEEPONFORK => libc.MADV_KEEPONFORK;
int get MADV_MERGEABLE => libc.MADV_MERGEABLE;
int get MADV_NOHUGEPAGE => libc.MADV_NOHUGEPAGE;
int get MADV_NORMAL => libc.MADV_NORMAL;
int get MADV_RANDOM => libc.MADV_RANDOM;
int get MADV_REMOVE => libc.MADV_REMOVE;
int get MADV_SEQUENTIAL => libc.MADV_SEQUENTIAL;
int get MADV_UNMERGEABLE => libc.MADV_UNMERGEABLE;
int get MADV_WILLNEED => libc.MADV_WILLNEED;
int get MADV_WIPEONFORK => libc.MADV_WIPEONFORK;
int get MAP_32BIT => libc.MAP_32BIT;
int get MAP_ANON => libc.MAP_ANON;
int get MAP_ANONYMOUS => libc.MAP_ANONYMOUS;
int get MAP_DENYWRITE => libc.MAP_DENYWRITE;
int get MAP_EXECUTABLE => libc.MAP_EXECUTABLE;
int get MAP_FILE => libc.MAP_FILE;
int get MAP_FIXED => libc.MAP_FIXED;
int get MAP_GROWSDOWN => libc.MAP_GROWSDOWN;
int get MAP_HUGETLB => libc.MAP_HUGETLB;
int get MAP_HUGE_MASK => libc.MAP_HUGE_MASK;
int get MAP_HUGE_SHIFT => libc.MAP_HUGE_SHIFT;
int get MAP_LOCKED => libc.MAP_LOCKED;
int get MAP_NONBLOCK => libc.MAP_NONBLOCK;
int get MAP_NORESERVE => libc.MAP_NORESERVE;
int get MAP_POPULATE => libc.MAP_POPULATE;
int get MAP_PRIVATE => libc.MAP_PRIVATE;
int get MAP_SHARED => libc.MAP_SHARED;
int get MAP_STACK => libc.MAP_STACK;
int get MAP_TYPE => libc.MAP_TYPE;
int get MCL_CURRENT => libc.MCL_CURRENT;
int get MCL_FUTURE => libc.MCL_FUTURE;
int get MCL_ONFAULT => libc.MCL_ONFAULT;
int get MS_ASYNC => libc.MS_ASYNC;
int get MS_INVALIDATE => libc.MS_INVALIDATE;
int get MS_SYNC => libc.MS_SYNC;
int get NFDBITS => libc.NFDBITS;
int get NULL => libc.NULL;
int get O_ACCMODE => libc.O_ACCMODE;
int get O_APPEND => libc.O_APPEND;
int get O_ASYNC => libc.O_ASYNC;
int get O_CLOEXEC => libc.O_CLOEXEC;
int get O_CREAT => libc.O_CREAT;
int get O_DIRECTORY => libc.O_DIRECTORY;
int get O_DSYNC => libc.O_DSYNC;
int get O_EXCL => libc.O_EXCL;
int get O_FSYNC => libc.O_FSYNC;
int get O_NDELAY => libc.O_NDELAY;
int get O_NOCTTY => libc.O_NOCTTY;
int get O_NOFOLLOW => libc.O_NOFOLLOW;
int get O_NONBLOCK => libc.O_NONBLOCK;
int get O_RDONLY => libc.O_RDONLY;
int get O_RDWR => libc.O_RDWR;
int get O_RSYNC => libc.O_RSYNC;
int get O_SYNC => libc.O_SYNC;
int get O_TRUNC => libc.O_TRUNC;
int get O_WRONLY => libc.O_WRONLY;
int get PDP_ENDIAN => libc.PDP_ENDIAN;
int get POSIX_FADV_DONTNEED => libc.POSIX_FADV_DONTNEED;
int get POSIX_FADV_NOREUSE => libc.POSIX_FADV_NOREUSE;
int get POSIX_FADV_NORMAL => libc.POSIX_FADV_NORMAL;
int get POSIX_FADV_RANDOM => libc.POSIX_FADV_RANDOM;
int get POSIX_FADV_SEQUENTIAL => libc.POSIX_FADV_SEQUENTIAL;
int get POSIX_FADV_WILLNEED => libc.POSIX_FADV_WILLNEED;
int get POSIX_MADV_DONTNEED => libc.POSIX_MADV_DONTNEED;
int get POSIX_MADV_NORMAL => libc.POSIX_MADV_NORMAL;
int get POSIX_MADV_RANDOM => libc.POSIX_MADV_RANDOM;
int get POSIX_MADV_SEQUENTIAL => libc.POSIX_MADV_SEQUENTIAL;
int get POSIX_MADV_WILLNEED => libc.POSIX_MADV_WILLNEED;
int get PROT_EXEC => libc.PROT_EXEC;
int get PROT_GROWSDOWN => libc.PROT_GROWSDOWN;
int get PROT_GROWSUP => libc.PROT_GROWSUP;
int get PROT_NONE => libc.PROT_NONE;
int get PROT_READ => libc.PROT_READ;
int get PROT_WRITE => libc.PROT_WRITE;
int get RAND_MAX => libc.RAND_MAX;
int get R_OK => libc.R_OK;
int get SEEK_CUR => libc.SEEK_CUR;
int get SEEK_END => libc.SEEK_END;
int get SEEK_SET => libc.SEEK_SET;
int get SI_LOAD_SHIFT => libc.SI_LOAD_SHIFT;
int get STAT_VER => libc.STAT_VER;
int get STDERR_FILENO => libc.STDERR_FILENO;
int get STDIN_FILENO => libc.STDIN_FILENO;
int get STDOUT_FILENO => libc.STDOUT_FILENO;
int get SYS_NMLN => libc.SYS_NMLN;
int get S_BLKSIZE => libc.S_BLKSIZE;
int get S_IEXEC => libc.S_IEXEC;
int get S_IFBLK => libc.S_IFBLK;
int get S_IFCHR => libc.S_IFCHR;
int get S_IFDIR => libc.S_IFDIR;
int get S_IFIFO => libc.S_IFIFO;
int get S_IFLNK => libc.S_IFLNK;
int get S_IFMT => libc.S_IFMT;
int get S_IFREG => libc.S_IFREG;
int get S_IFSOCK => libc.S_IFSOCK;
int get S_IREAD => libc.S_IREAD;
int get S_IRGRP => libc.S_IRGRP;
int get S_IROTH => libc.S_IROTH;
int get S_IRUSR => libc.S_IRUSR;
int get S_IRWXG => libc.S_IRWXG;
int get S_IRWXO => libc.S_IRWXO;
int get S_IRWXU => libc.S_IRWXU;
int get S_ISGID => libc.S_ISGID;
int get S_ISUID => libc.S_ISUID;
int get S_ISVTX => libc.S_ISVTX;
int get S_IWGRP => libc.S_IWGRP;
int get S_IWOTH => libc.S_IWOTH;
int get S_IWRITE => libc.S_IWRITE;
int get S_IWUSR => libc.S_IWUSR;
int get S_IXGRP => libc.S_IXGRP;
int get S_IXOTH => libc.S_IXOTH;
int get S_IXUSR => libc.S_IXUSR;
int get UTIME_NOW => libc.UTIME_NOW;
int get UTIME_OMIT => libc.UTIME_OMIT;
int get UTSNAME_DOMAIN_LENGTH => libc.UTSNAME_DOMAIN_LENGTH;
int get UTSNAME_LENGTH => libc.UTSNAME_LENGTH;
int get UTSNAME_MACHINE_LENGTH => libc.UTSNAME_MACHINE_LENGTH;
int get UTSNAME_NODENAME_LENGTH => libc.UTSNAME_NODENAME_LENGTH;
int get UTSNAME_RELEASE_LENGTH => libc.UTSNAME_RELEASE_LENGTH;
int get UTSNAME_SYSNAME_LENGTH => libc.UTSNAME_SYSNAME_LENGTH;
int get UTSNAME_VERSION_LENGTH => libc.UTSNAME_VERSION_LENGTH;
int get WCONTINUED => libc.WCONTINUED;
int get WEXITED => libc.WEXITED;
int get WNOHANG => libc.WNOHANG;
int get WNOWAIT => libc.WNOWAIT;
int get WRDE_APPEND => libc.WRDE_APPEND;
int get WRDE_BADCHAR => libc.WRDE_BADCHAR;
int get WRDE_BADVAL => libc.WRDE_BADVAL;
int get WRDE_CMDSUB => libc.WRDE_CMDSUB;
int get WRDE_DOOFFS => libc.WRDE_DOOFFS;
int get WRDE_NOCMD => libc.WRDE_NOCMD;
int get WRDE_NOSPACE => libc.WRDE_NOSPACE;
int get WRDE_REUSE => libc.WRDE_REUSE;
int get WRDE_SHOWERR => libc.WRDE_SHOWERR;
int get WRDE_SYNTAX => libc.WRDE_SYNTAX;
int get WRDE_UNDEF => libc.WRDE_UNDEF;
int get WSTOPPED => libc.WSTOPPED;
int get WUNTRACED => libc.WUNTRACED;
int get W_OK => libc.W_OK;
int get X_OK => libc.X_OK;
mixin MacroMixin {
  int get ACCESSPERMS;
  int get ALLPERMS;
  int get AT_EACCESS;
  int get AT_FDCWD;
  int get AT_REMOVEDIR;
  int get AT_SYMLINK_FOLLOW;
  int get AT_SYMLINK_NOFOLLOW;
  int get BIG_ENDIAN;
  int get BYTE_ORDER;
  int get DEFFILEMODE;
  int get E2BIG;
  int get EACCES;
  int get EADDRINUSE;
  int get EADDRNOTAVAIL;
  int get EADV;
  int get EAFNOSUPPORT;
  int get EAGAIN;
  int get EALREADY;
  int get EBADE;
  int get EBADF;
  int get EBADFD;
  int get EBADMSG;
  int get EBADR;
  int get EBADRQC;
  int get EBADSLT;
  int get EBFONT;
  int get EBUSY;
  int get ECANCELED;
  int get ECHILD;
  int get ECHRNG;
  int get ECOMM;
  int get ECONNABORTED;
  int get ECONNREFUSED;
  int get ECONNRESET;
  int get EDEADLK;
  int get EDEADLOCK;
  int get EDESTADDRREQ;
  int get EDOM;
  int get EDOTDOT;
  int get EDQUOT;
  int get EEXIST;
  int get EFAULT;
  int get EFBIG;
  int get EHOSTDOWN;
  int get EHOSTUNREACH;
  int get EHWPOISON;
  int get EIDRM;
  int get EILSEQ;
  int get EINPROGRESS;
  int get EINTR;
  int get EINVAL;
  int get EIO;
  int get EISCONN;
  int get EISDIR;
  int get EISNAM;
  int get EKEYEXPIRED;
  int get EKEYREJECTED;
  int get EKEYREVOKED;
  int get EL2HLT;
  int get EL2NSYNC;
  int get EL3HLT;
  int get EL3RST;
  int get ELIBACC;
  int get ELIBBAD;
  int get ELIBEXEC;
  int get ELIBMAX;
  int get ELIBSCN;
  int get ELNRNG;
  int get ELOOP;
  int get EMEDIUMTYPE;
  int get EMFILE;
  int get EMLINK;
  int get EMSGSIZE;
  int get EMULTIHOP;
  int get ENAMETOOLONG;
  int get ENAVAIL;
  int get ENETDOWN;
  int get ENETRESET;
  int get ENETUNREACH;
  int get ENFILE;
  int get ENOANO;
  int get ENOBUFS;
  int get ENOCSI;
  int get ENODATA;
  int get ENODEV;
  int get ENOENT;
  int get ENOEXEC;
  int get ENOKEY;
  int get ENOLCK;
  int get ENOLINK;
  int get ENOMEDIUM;
  int get ENOMEM;
  int get ENOMSG;
  int get ENONET;
  int get ENOPKG;
  int get ENOPROTOOPT;
  int get ENOSPC;
  int get ENOSR;
  int get ENOSTR;
  int get ENOSYS;
  int get ENOTBLK;
  int get ENOTCONN;
  int get ENOTDIR;
  int get ENOTEMPTY;
  int get ENOTNAM;
  int get ENOTRECOVERABLE;
  int get ENOTSOCK;
  int get ENOTSUP;
  int get ENOTTY;
  int get ENOTUNIQ;
  int get ENXIO;
  int get EOPNOTSUPP;
  int get EOVERFLOW;
  int get EOWNERDEAD;
  int get EPERM;
  int get EPFNOSUPPORT;
  int get EPIPE;
  int get EPROTO;
  int get EPROTONOSUPPORT;
  int get EPROTOTYPE;
  int get ERANGE;
  int get EREMCHG;
  int get EREMOTE;
  int get EREMOTEIO;
  int get ERESTART;
  int get ERFKILL;
  int get EROFS;
  int get ESHUTDOWN;
  int get ESOCKTNOSUPPORT;
  int get ESPIPE;
  int get ESRCH;
  int get ESRMNT;
  int get ESTALE;
  int get ESTRPIPE;
  int get ETIME;
  int get ETIMEDOUT;
  int get ETOOMANYREFS;
  int get ETXTBSY;
  int get EUCLEAN;
  int get EUNATCH;
  int get EUSERS;
  int get EWOULDBLOCK;
  int get EXDEV;
  int get EXFULL;
  int get EXIT_FAILURE;
  int get EXIT_SUCCESS;
  int get FAPPEND;
  int get FASYNC;
  int get FD_CLOEXEC;
  int get FD_SETSIZE;
  int get FFSYNC;
  int get FNDELAY;
  int get FNM_CASEFOLD;
  int get FNM_EXTMATCH;
  int get FNM_FILE_NAME;
  int get FNM_LEADING_DIR;
  int get FNM_NOESCAPE;
  int get FNM_NOMATCH;
  int get FNM_PATHNAME;
  int get FNM_PERIOD;
  int get FNONBLOCK;
  int get F_DUPFD;
  int get F_DUPFD_CLOEXEC;
  int get F_EXLCK;
  int get F_GETFD;
  int get F_GETFL;
  int get F_GETLK;
  int get F_GETLK64;
  int get F_GETOWN;
  int get F_LOCK;
  int get F_OK;
  int get F_RDLCK;
  int get F_SETFD;
  int get F_SETFL;
  int get F_SETLK;
  int get F_SETLK64;
  int get F_SETLKW;
  int get F_SETLKW64;
  int get F_SETOWN;
  int get F_SHLCK;
  int get F_TEST;
  int get F_TLOCK;
  int get F_ULOCK;
  int get F_UNLCK;
  int get F_WRLCK;
  int get GLOB_ABORTED;
  int get GLOB_ALTDIRFUNC;
  int get GLOB_APPEND;
  int get GLOB_BRACE;
  int get GLOB_DOOFFS;
  int get GLOB_ERR;
  int get GLOB_MAGCHAR;
  int get GLOB_MARK;
  int get GLOB_NOCHECK;
  int get GLOB_NOESCAPE;
  int get GLOB_NOMAGIC;
  int get GLOB_NOMATCH;
  int get GLOB_NOSORT;
  int get GLOB_NOSPACE;
  int get GLOB_NOSYS;
  int get GLOB_ONLYDIR;
  int get GLOB_PERIOD;
  int get GLOB_TILDE;
  int get GLOB_TILDE_CHECK;
  int get LITTLE_ENDIAN;
  int get LOCK_EX;
  int get LOCK_NB;
  int get LOCK_SH;
  int get LOCK_UN;
  int get LOG_ALERT;
  int get LOG_AUTH;
  int get LOG_AUTHPRIV;
  int get LOG_CONS;
  int get LOG_CRIT;
  int get LOG_CRON;
  int get LOG_DAEMON;
  int get LOG_DEBUG;
  int get LOG_EMERG;
  int get LOG_ERR;
  int get LOG_FACMASK;
  int get LOG_FTP;
  int get LOG_INFO;
  int get LOG_KERN;
  int get LOG_LOCAL0;
  int get LOG_LOCAL1;
  int get LOG_LOCAL2;
  int get LOG_LOCAL3;
  int get LOG_LOCAL4;
  int get LOG_LOCAL5;
  int get LOG_LOCAL6;
  int get LOG_LOCAL7;
  int get LOG_LPR;
  int get LOG_MAIL;
  int get LOG_NDELAY;
  int get LOG_NEWS;
  int get LOG_NFACILITIES;
  int get LOG_NOTICE;
  int get LOG_NOWAIT;
  int get LOG_ODELAY;
  int get LOG_PERROR;
  int get LOG_PID;
  int get LOG_PRIMASK;
  int get LOG_SYSLOG;
  int get LOG_USER;
  int get LOG_UUCP;
  int get LOG_WARNING;
  int get L_INCR;
  int get L_SET;
  int get L_XTND;
  int get MADV_DODUMP;
  int get MADV_DOFORK;
  int get MADV_DONTDUMP;
  int get MADV_DONTFORK;
  int get MADV_DONTNEED;
  int get MADV_FREE;
  int get MADV_HUGEPAGE;
  int get MADV_HWPOISON;
  int get MADV_KEEPONFORK;
  int get MADV_MERGEABLE;
  int get MADV_NOHUGEPAGE;
  int get MADV_NORMAL;
  int get MADV_RANDOM;
  int get MADV_REMOVE;
  int get MADV_SEQUENTIAL;
  int get MADV_UNMERGEABLE;
  int get MADV_WILLNEED;
  int get MADV_WIPEONFORK;
  int get MAP_32BIT;
  int get MAP_ANON;
  int get MAP_ANONYMOUS;
  int get MAP_DENYWRITE;
  int get MAP_EXECUTABLE;
  int get MAP_FILE;
  int get MAP_FIXED;
  int get MAP_GROWSDOWN;
  int get MAP_HUGETLB;
  int get MAP_HUGE_MASK;
  int get MAP_HUGE_SHIFT;
  int get MAP_LOCKED;
  int get MAP_NONBLOCK;
  int get MAP_NORESERVE;
  int get MAP_POPULATE;
  int get MAP_PRIVATE;
  int get MAP_SHARED;
  int get MAP_STACK;
  int get MAP_TYPE;
  int get MCL_CURRENT;
  int get MCL_FUTURE;
  int get MCL_ONFAULT;
  int get MS_ASYNC;
  int get MS_INVALIDATE;
  int get MS_SYNC;
  int get NFDBITS;
  int get NULL;
  int get O_ACCMODE;
  int get O_APPEND;
  int get O_ASYNC;
  int get O_CLOEXEC;
  int get O_CREAT;
  int get O_DIRECTORY;
  int get O_DSYNC;
  int get O_EXCL;
  int get O_FSYNC;
  int get O_NDELAY;
  int get O_NOCTTY;
  int get O_NOFOLLOW;
  int get O_NONBLOCK;
  int get O_RDONLY;
  int get O_RDWR;
  int get O_RSYNC;
  int get O_SYNC;
  int get O_TRUNC;
  int get O_WRONLY;
  int get PDP_ENDIAN;
  int get POSIX_FADV_DONTNEED;
  int get POSIX_FADV_NOREUSE;
  int get POSIX_FADV_NORMAL;
  int get POSIX_FADV_RANDOM;
  int get POSIX_FADV_SEQUENTIAL;
  int get POSIX_FADV_WILLNEED;
  int get POSIX_MADV_DONTNEED;
  int get POSIX_MADV_NORMAL;
  int get POSIX_MADV_RANDOM;
  int get POSIX_MADV_SEQUENTIAL;
  int get POSIX_MADV_WILLNEED;
  int get PROT_EXEC;
  int get PROT_GROWSDOWN;
  int get PROT_GROWSUP;
  int get PROT_NONE;
  int get PROT_READ;
  int get PROT_WRITE;
  int get RAND_MAX;
  int get R_OK;
  int get SEEK_CUR;
  int get SEEK_END;
  int get SEEK_SET;
  int get SI_LOAD_SHIFT;
  int get STAT_VER;
  int get STDERR_FILENO;
  int get STDIN_FILENO;
  int get STDOUT_FILENO;
  int get SYS_NMLN;
  int get S_BLKSIZE;
  int get S_IEXEC;
  int get S_IFBLK;
  int get S_IFCHR;
  int get S_IFDIR;
  int get S_IFIFO;
  int get S_IFLNK;
  int get S_IFMT;
  int get S_IFREG;
  int get S_IFSOCK;
  int get S_IREAD;
  int get S_IRGRP;
  int get S_IROTH;
  int get S_IRUSR;
  int get S_IRWXG;
  int get S_IRWXO;
  int get S_IRWXU;
  int get S_ISGID;
  int get S_ISUID;
  int get S_ISVTX;
  int get S_IWGRP;
  int get S_IWOTH;
  int get S_IWRITE;
  int get S_IWUSR;
  int get S_IXGRP;
  int get S_IXOTH;
  int get S_IXUSR;
  int get UTIME_NOW;
  int get UTIME_OMIT;
  int get UTSNAME_DOMAIN_LENGTH;
  int get UTSNAME_LENGTH;
  int get UTSNAME_MACHINE_LENGTH;
  int get UTSNAME_NODENAME_LENGTH;
  int get UTSNAME_RELEASE_LENGTH;
  int get UTSNAME_SYSNAME_LENGTH;
  int get UTSNAME_VERSION_LENGTH;
  int get WCONTINUED;
  int get WEXITED;
  int get WNOHANG;
  int get WNOWAIT;
  int get WRDE_APPEND;
  int get WRDE_BADCHAR;
  int get WRDE_BADVAL;
  int get WRDE_CMDSUB;
  int get WRDE_DOOFFS;
  int get WRDE_NOCMD;
  int get WRDE_NOSPACE;
  int get WRDE_REUSE;
  int get WRDE_SHOWERR;
  int get WRDE_SYNTAX;
  int get WRDE_UNDEF;
  int get WSTOPPED;
  int get WUNTRACED;
  int get W_OK;
  int get X_OK;
}
