// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;
import 'sysinfo_t.dart' as sysinfo_t;

/// GNU C Library
class GnuLibC {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GnuLibC(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GnuLibC.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Int> errno() {
    return _errno();
  }

  late final _errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>(
          '__errno_location');
  late final _errno = _errnoPtr.asFunction<ffi.Pointer<ffi.Int> Function()>();

  int fstat(
    int __ver,
    int __fildes,
    ffi.Pointer<stat_t> __stat_buf,
  ) {
    return _fstat(
      __ver,
      __fildes,
      __stat_buf,
    );
  }

  late final _fstatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Int, ffi.Pointer<stat_t>)>>('__fxstat');
  late final _fstat =
      _fstatPtr.asFunction<int Function(int, int, ffi.Pointer<stat_t>)>();

  int glob(
    ffi.Pointer<ffi.Char> __pattern,
    int __flags,
    ffi.Pointer<
            ffi
            .NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>>
        __errfunc,
    ffi.Pointer<glob_t> __pglob,
  ) {
    return _glob(
      __pattern,
      __flags,
      __errfunc,
      __pglob,
    );
  }

  late final _globPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Int,
              ffi.Pointer<
                  ffi.NativeFunction<
                      ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>>,
              ffi.Pointer<glob_t>)>>('glob');
  late final _glob = _globPtr.asFunction<
      int Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<
              ffi.NativeFunction<
                  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>>,
          ffi.Pointer<glob_t>)>();

  void globfree(
    ffi.Pointer<glob_t> __pglob,
  ) {
    return _globfree(
      __pglob,
    );
  }

  late final _globfreePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<glob_t>)>>(
          'globfree');
  late final _globfree =
      _globfreePtr.asFunction<void Function(ffi.Pointer<glob_t>)>();

  int lstat(
    int __ver,
    ffi.Pointer<ffi.Char> __filename,
    ffi.Pointer<stat_t> __stat_buf,
  ) {
    return _lstat(
      __ver,
      __filename,
      __stat_buf,
    );
  }

  late final _lstatPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Int, ffi.Pointer<ffi.Char>,
              ffi.Pointer<stat_t>)>>('__lxstat');
  late final _lstat = _lstatPtr.asFunction<
      int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<stat_t>)>();

  ffi.Pointer<ffi.Void> mmap(
    ffi.Pointer<ffi.Void> __addr,
    int __len,
    int __prot,
    int __flags,
    int __fd,
    int __offset,
  ) {
    return _mmap(
      __addr,
      __len,
      __prot,
      __flags,
      __fd,
      __offset,
    );
  }

  late final _mmapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size,
              ffi.Int, ffi.Int, ffi.Int, ffi.Long)>>('mmap');
  late final _mmap = _mmapPtr.asFunction<
      ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void>, int, int, int, int, int)>();

  int munmap(
    ffi.Pointer<ffi.Void> __addr,
    int __len,
  ) {
    return _munmap(
      __addr,
      __len,
    );
  }

  late final _munmapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Size)>>('munmap');
  late final _munmap =
      _munmapPtr.asFunction<int Function(ffi.Pointer<ffi.Void>, int)>();

  int stat(
    int __ver,
    ffi.Pointer<ffi.Char> __filename,
    ffi.Pointer<stat_t> __stat_buf,
  ) {
    return _stat(
      __ver,
      __filename,
      __stat_buf,
    );
  }

  late final _statPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Int, ffi.Pointer<ffi.Char>, ffi.Pointer<stat_t>)>>('__xstat');
  late final _stat = _statPtr.asFunction<
      int Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<stat_t>)>();

  int sysinfo(
    ffi.Pointer<sysinfo_t.sysinfo_t> __info,
  ) {
    return _sysinfo(
      __info,
    );
  }

  late final _sysinfoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<sysinfo_t.sysinfo_t>)>>('sysinfo');
  late final _sysinfo =
      _sysinfoPtr.asFunction<int Function(ffi.Pointer<sysinfo_t.sysinfo_t>)>();

  int uname(
    ffi.Pointer<utsname_t> __name,
  ) {
    return _uname(
      __name,
    );
  }

  late final _unamePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<utsname_t>)>>(
          'uname');
  late final _uname =
      _unamePtr.asFunction<int Function(ffi.Pointer<utsname_t>)>();
}

const int ACCESSPERMS = 511;

const int ACCOUNTING = 9;

const int ALLPERMS = 4095;

const int AT_EACCESS = 512;

const int AT_FDCWD = -100;

const int AT_REMOVEDIR = 512;

const int AT_SYMLINK_FOLLOW = 1024;

const int AT_SYMLINK_NOFOLLOW = 256;

const int BIG_ENDIAN = 4321;

const int BOOT_TIME = 2;

const int BYTE_ORDER = 1234;

const int CBRK = 0;

const int CDISCARD = 15;

const int CDSUSP = 25;

const int CEOF = 4;

const int CEOL = 0;

const int CEOT = 4;

const int CERASE = 127;

const int CFLUSH = 15;

const int CINTR = 3;

const int CKILL = 21;

const int CLNEXT = 22;

const int CMIN = 1;

const int CQUIT = 28;

const int CREPRINT = 18;

const int CRPRNT = 18;

const int CSTART = 17;

const int CSTATUS = 0;

const int CSTOP = 19;

const int CSUSP = 26;

const int CTIME = 0;

const int CWERASE = 23;

const int DEAD_PROCESS = 8;

const int DEFFILEMODE = 438;

const int E2BIG = 7;

const int EACCES = 13;

const int EADDRINUSE = 98;

const int EADDRNOTAVAIL = 99;

const int EADV = 68;

const int EAFNOSUPPORT = 97;

const int EAGAIN = 11;

const int EALREADY = 114;

const int EBADE = 52;

const int EBADF = 9;

const int EBADFD = 77;

const int EBADMSG = 74;

const int EBADR = 53;

const int EBADRQC = 56;

const int EBADSLT = 57;

const int EBFONT = 59;

const int EBUSY = 16;

const int ECANCELED = 125;

const int ECHILD = 10;

const int ECHRNG = 44;

const int ECOMM = 70;

const int ECONNABORTED = 103;

const int ECONNREFUSED = 111;

const int ECONNRESET = 104;

const int EDEADLK = 35;

const int EDEADLOCK = 35;

const int EDESTADDRREQ = 89;

const int EDOM = 33;

const int EDOTDOT = 73;

const int EDQUOT = 122;

const int EEXIST = 17;

const int EFAULT = 14;

const int EFBIG = 27;

const int EHOSTDOWN = 112;

const int EHOSTUNREACH = 113;

const int EHWPOISON = 133;

const int EIDRM = 43;

const int EILSEQ = 84;

const int EINPROGRESS = 115;

const int EINTR = 4;

const int EINVAL = 22;

const int EIO = 5;

const int EISCONN = 106;

const int EISDIR = 21;

const int EISNAM = 120;

const int EKEYEXPIRED = 127;

const int EKEYREJECTED = 129;

const int EKEYREVOKED = 128;

const int EL2HLT = 51;

const int EL2NSYNC = 45;

const int EL3HLT = 46;

const int EL3RST = 47;

const int ELIBACC = 79;

const int ELIBBAD = 80;

const int ELIBEXEC = 83;

const int ELIBMAX = 82;

const int ELIBSCN = 81;

const int ELNRNG = 48;

const int ELOOP = 40;

const int EMEDIUMTYPE = 124;

const int EMFILE = 24;

const int EMLINK = 31;

const int EMPTY = 0;

const int EMSGSIZE = 90;

const int EMULTIHOP = 72;

const int ENAMETOOLONG = 36;

const int ENAVAIL = 119;

const int ENETDOWN = 100;

const int ENETRESET = 102;

const int ENETUNREACH = 101;

const int ENFILE = 23;

const int ENOANO = 55;

const int ENOBUFS = 105;

const int ENOCSI = 50;

const int ENODATA = 61;

const int ENODEV = 19;

const int ENOENT = 2;

const int ENOEXEC = 8;

const int ENOKEY = 126;

const int ENOLCK = 37;

const int ENOLINK = 67;

const int ENOMEDIUM = 123;

const int ENOMEM = 12;

const int ENOMSG = 42;

const int ENONET = 64;

const int ENOPKG = 65;

const int ENOPROTOOPT = 92;

const int ENOSPC = 28;

const int ENOSR = 63;

const int ENOSTR = 60;

const int ENOSYS = 38;

const int ENOTBLK = 15;

const int ENOTCONN = 107;

const int ENOTDIR = 20;

const int ENOTEMPTY = 39;

const int ENOTNAM = 118;

const int ENOTRECOVERABLE = 131;

const int ENOTSOCK = 88;

const int ENOTSUP = 95;

const int ENOTTY = 25;

const int ENOTUNIQ = 76;

const int ENXIO = 6;

const int EOPNOTSUPP = 95;

const int EOVERFLOW = 75;

const int EOWNERDEAD = 130;

const int EPERM = 1;

const int EPFNOSUPPORT = 96;

const int EPIPE = 32;

const int EPROTO = 71;

const int EPROTONOSUPPORT = 93;

const int EPROTOTYPE = 91;

const int ERANGE = 34;

const int EREMCHG = 78;

const int EREMOTE = 66;

const int EREMOTEIO = 121;

const int ERESTART = 85;

const int ERFKILL = 132;

const int EROFS = 30;

const int ESHUTDOWN = 108;

const int ESOCKTNOSUPPORT = 94;

const int ESPIPE = 29;

const int ESRCH = 3;

const int ESRMNT = 69;

const int ESTALE = 116;

const int ESTRPIPE = 86;

const int ETIME = 62;

const int ETIMEDOUT = 110;

const int ETOOMANYREFS = 109;

const int ETXTBSY = 26;

const int EUCLEAN = 117;

const int EUNATCH = 49;

const int EUSERS = 87;

const int EWOULDBLOCK = 11;

const int EXDEV = 18;

const int EXFULL = 54;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int FAPPEND = 1024;

const int FASYNC = 8192;

const int FD_CLOEXEC = 1;

const int FD_SETSIZE = 1024;

const int FFSYNC = 1052672;

const int FIOASYNC = 21586;

const int FIOCLEX = 21585;

const int FIONBIO = 21537;

const int FIONCLEX = 21584;

const int FIONREAD = 21531;

const int FIOQSIZE = 21600;

const int FNDELAY = 2048;

const int FNM_CASEFOLD = 16;

const int FNM_EXTMATCH = 32;

const int FNM_FILE_NAME = 1;

const int FNM_LEADING_DIR = 8;

const int FNM_NOESCAPE = 2;

const int FNM_NOMATCH = 1;

const int FNM_PATHNAME = 1;

const int FNM_PERIOD = 4;

const int FNONBLOCK = 2048;

const String FSTAB = '/etc/fstab';

const String FSTAB_RO = 'ro';

const String FSTAB_RQ = 'rq';

const String FSTAB_RW = 'rw';

const String FSTAB_SW = 'sw';

const String FSTAB_XX = 'xx';

const int F_DUPFD = 0;

const int F_DUPFD_CLOEXEC = 1030;

const int F_EXLCK = 4;

const int F_GETFD = 1;

const int F_GETFL = 3;

const int F_GETLK = 5;

const int F_GETLK64 = 5;

const int F_GETOWN = 9;

const int F_LOCK = 1;

const int F_OK = 0;

const int F_RDLCK = 0;

const int F_SETFD = 2;

const int F_SETFL = 4;

const int F_SETLK = 6;

const int F_SETLK64 = 6;

const int F_SETLKW = 7;

const int F_SETLKW64 = 7;

const int F_SETOWN = 8;

const int F_SHLCK = 8;

const int F_TEST = 3;

const int F_TLOCK = 2;

const int F_ULOCK = 0;

const int F_UNLCK = 2;

const int F_WRLCK = 1;

const int GLOB_ABORTED = 2;

const int GLOB_ALTDIRFUNC = 512;

const int GLOB_APPEND = 32;

const int GLOB_BRACE = 1024;

const int GLOB_DOOFFS = 8;

const int GLOB_ERR = 1;

const int GLOB_MAGCHAR = 256;

const int GLOB_MARK = 2;

const int GLOB_NOCHECK = 16;

const int GLOB_NOESCAPE = 64;

const int GLOB_NOMAGIC = 2048;

const int GLOB_NOMATCH = 3;

const int GLOB_NOSORT = 4;

const int GLOB_NOSPACE = 1;

const int GLOB_NOSYS = 4;

const int GLOB_ONLYDIR = 8192;

const int GLOB_PERIOD = 128;

const int GLOB_TILDE = 4096;

const int GLOB_TILDE_CHECK = 16384;

const int INIT_PROCESS = 5;

const int IOCSIZE_MASK = 1073676288;

const int IOCSIZE_SHIFT = 16;

const int IOC_IN = 1073741824;

const int IOC_INOUT = 3221225472;

const int IOC_OUT = 2147483648;

const int ITIMER_PROF = 2;

const int ITIMER_REAL = 0;

const int ITIMER_VIRTUAL = 1;

const int LITTLE_ENDIAN = 1234;

const int LOCK_EX = 2;

const int LOCK_NB = 4;

const int LOCK_SH = 1;

const int LOCK_UN = 8;

const int LOGIN_PROCESS = 6;

const int LOG_ALERT = 1;

const int LOG_AUTH = 32;

const int LOG_AUTHPRIV = 80;

const int LOG_CONS = 2;

const int LOG_CRIT = 2;

const int LOG_CRON = 72;

const int LOG_DAEMON = 24;

const int LOG_DEBUG = 7;

const int LOG_EMERG = 0;

const int LOG_ERR = 3;

const int LOG_FACMASK = 1016;

const int LOG_FTP = 88;

const int LOG_INFO = 6;

const int LOG_KERN = 0;

const int LOG_LOCAL0 = 128;

const int LOG_LOCAL1 = 136;

const int LOG_LOCAL2 = 144;

const int LOG_LOCAL3 = 152;

const int LOG_LOCAL4 = 160;

const int LOG_LOCAL5 = 168;

const int LOG_LOCAL6 = 176;

const int LOG_LOCAL7 = 184;

const int LOG_LPR = 48;

const int LOG_MAIL = 16;

const int LOG_NDELAY = 8;

const int LOG_NEWS = 56;

const int LOG_NFACILITIES = 24;

const int LOG_NOTICE = 5;

const int LOG_NOWAIT = 16;

const int LOG_ODELAY = 4;

const int LOG_PERROR = 32;

const int LOG_PID = 1;

const int LOG_PRIMASK = 7;

const int LOG_SYSLOG = 40;

const int LOG_USER = 8;

const int LOG_UUCP = 64;

const int LOG_WARNING = 4;

const int L_INCR = 1;

const int L_SET = 0;

const int L_XTND = 2;

const int MADV_COLD = 20;

const int MADV_DODUMP = 17;

const int MADV_DOFORK = 11;

const int MADV_DONTDUMP = 16;

const int MADV_DONTFORK = 10;

const int MADV_DONTNEED = 4;

const int MADV_FREE = 8;

const int MADV_HUGEPAGE = 14;

const int MADV_HWPOISON = 100;

const int MADV_KEEPONFORK = 19;

const int MADV_MERGEABLE = 12;

const int MADV_NOHUGEPAGE = 15;

const int MADV_NORMAL = 0;

const int MADV_PAGEOUT = 21;

const int MADV_RANDOM = 1;

const int MADV_REMOVE = 9;

const int MADV_SEQUENTIAL = 2;

const int MADV_UNMERGEABLE = 13;

const int MADV_WILLNEED = 3;

const int MADV_WIPEONFORK = 18;

const int MAP_32BIT = 64;

const int MAP_ANON = 32;

const int MAP_ANONYMOUS = 32;

const int MAP_DENYWRITE = 2048;

const int MAP_EXECUTABLE = 4096;

const int MAP_FILE = 0;

const int MAP_FIXED = 16;

const int MAP_FIXED_NOREPLACE = 1048576;

const int MAP_GROWSDOWN = 256;

const int MAP_HUGETLB = 262144;

const int MAP_HUGE_MASK = 63;

const int MAP_HUGE_SHIFT = 26;

const int MAP_LOCKED = 8192;

const int MAP_NONBLOCK = 65536;

const int MAP_NORESERVE = 16384;

const int MAP_POPULATE = 32768;

const int MAP_PRIVATE = 2;

const int MAP_SHARED = 1;

const int MAP_SHARED_VALIDATE = 3;

const int MAP_STACK = 131072;

const int MAP_SYNC = 524288;

const int MAP_TYPE = 15;

const int MCL_CURRENT = 1;

const int MCL_FUTURE = 2;

const int MCL_ONFAULT = 4;

const int MS_ASYNC = 1;

const int MS_INVALIDATE = 2;

const int MS_SYNC = 4;

const int NCC = 8;

const int NEW_TIME = 3;

const int NFDBITS = 64;

const int NSS_BUFLEN_PASSWD = 1024;

const int NULL = 0;

const int N_6PACK = 7;

const int N_AX25 = 5;

const int N_HCI = 15;

const int N_HDLC = 13;

const int N_IRDA = 11;

const int N_MASC = 8;

const int N_MOUSE = 2;

const int N_PPP = 3;

const int N_PROFIBUS_FDL = 10;

const int N_R3964 = 9;

const int N_SLIP = 1;

const int N_SMSBLOCK = 12;

const int N_STRIP = 4;

const int N_SYNC_PPP = 14;

const int N_TTY = 0;

const int N_X25 = 6;

const int OLD_TIME = 4;

const int O_ACCMODE = 3;

const int O_APPEND = 1024;

const int O_ASYNC = 8192;

const int O_CLOEXEC = 524288;

const int O_CREAT = 64;

const int O_DIRECTORY = 65536;

const int O_DSYNC = 4096;

const int O_EXCL = 128;

const int O_FSYNC = 1052672;

const int O_NDELAY = 2048;

const int O_NOCTTY = 256;

const int O_NOFOLLOW = 131072;

const int O_NONBLOCK = 2048;

const int O_RDONLY = 0;

const int O_RDWR = 2;

const int O_RSYNC = 1052672;

const int O_SYNC = 1052672;

const int O_TRUNC = 512;

const int O_WRONLY = 1;

const int PDP_ENDIAN = 3412;

const int POLLERR = 8;

const int POLLHUP = 16;

const int POLLIN = 1;

const int POLLNVAL = 32;

const int POLLOUT = 4;

const int POLLPRI = 2;

const int POLLRDBAND = 128;

const int POLLRDNORM = 64;

const int POLLWRBAND = 512;

const int POLLWRNORM = 256;

const int POSIX_FADV_DONTNEED = 4;

const int POSIX_FADV_NOREUSE = 5;

const int POSIX_FADV_NORMAL = 0;

const int POSIX_FADV_RANDOM = 1;

const int POSIX_FADV_SEQUENTIAL = 2;

const int POSIX_FADV_WILLNEED = 3;

const int POSIX_MADV_DONTNEED = 4;

const int POSIX_MADV_NORMAL = 0;

const int POSIX_MADV_RANDOM = 1;

const int POSIX_MADV_SEQUENTIAL = 2;

const int POSIX_MADV_WILLNEED = 3;

const int PROT_EXEC = 4;

const int PROT_GROWSDOWN = 16777216;

const int PROT_GROWSUP = 33554432;

const int PROT_NONE = 0;

const int PROT_READ = 1;

const int PROT_WRITE = 2;

const int RAND_MAX = 2147483647;

const int RUN_LVL = 1;

const int R_OK = 4;

const int SEEK_CUR = 1;

const int SEEK_END = 2;

const int SEEK_SET = 0;

const int SIOCADDDLCI = 35200;

const int SIOCADDMULTI = 35121;

const int SIOCADDRT = 35083;

const int SIOCDARP = 35155;

const int SIOCDELDLCI = 35201;

const int SIOCDELMULTI = 35122;

const int SIOCDELRT = 35084;

const int SIOCDEVPRIVATE = 35312;

const int SIOCDIFADDR = 35126;

const int SIOCDRARP = 35168;

const int SIOCGARP = 35156;

const int SIOCGIFADDR = 35093;

const int SIOCGIFBR = 35136;

const int SIOCGIFBRDADDR = 35097;

const int SIOCGIFCONF = 35090;

const int SIOCGIFCOUNT = 35128;

const int SIOCGIFDSTADDR = 35095;

const int SIOCGIFENCAP = 35109;

const int SIOCGIFFLAGS = 35091;

const int SIOCGIFHWADDR = 35111;

const int SIOCGIFINDEX = 35123;

const int SIOCGIFMAP = 35184;

const int SIOCGIFMEM = 35103;

const int SIOCGIFMETRIC = 35101;

const int SIOCGIFMTU = 35105;

const int SIOCGIFNAME = 35088;

const int SIOCGIFNETMASK = 35099;

const int SIOCGIFPFLAGS = 35125;

const int SIOCGIFSLAVE = 35113;

const int SIOCGIFTXQLEN = 35138;

const int SIOCGRARP = 35169;

const int SIOCPROTOPRIVATE = 35296;

const int SIOCRTMSG = 35085;

const int SIOCSARP = 35157;

const int SIOCSIFADDR = 35094;

const int SIOCSIFBR = 35137;

const int SIOCSIFBRDADDR = 35098;

const int SIOCSIFDSTADDR = 35096;

const int SIOCSIFENCAP = 35110;

const int SIOCSIFFLAGS = 35092;

const int SIOCSIFHWADDR = 35108;

const int SIOCSIFHWBROADCAST = 35127;

const int SIOCSIFLINK = 35089;

const int SIOCSIFMAP = 35185;

const int SIOCSIFMEM = 35104;

const int SIOCSIFMETRIC = 35102;

const int SIOCSIFMTU = 35106;

const int SIOCSIFNAME = 35107;

const int SIOCSIFNETMASK = 35100;

const int SIOCSIFPFLAGS = 35124;

const int SIOCSIFSLAVE = 35120;

const int SIOCSIFTXQLEN = 35139;

const int SIOCSRARP = 35170;

const int SIOGIFINDEX = 35123;

const int SI_LOAD_SHIFT = 16;

const int STAT_VER = 1;

const int STDERR_FILENO = 2;

const int STDIN_FILENO = 0;

const int STDOUT_FILENO = 1;

const int SYS_NMLN = 65;

const int S_BLKSIZE = 512;

const int S_IEXEC = 64;

const int S_IFBLK = 24576;

const int S_IFCHR = 8192;

const int S_IFDIR = 16384;

const int S_IFIFO = 4096;

const int S_IFLNK = 40960;

const int S_IFMT = 61440;

const int S_IFREG = 32768;

const int S_IFSOCK = 49152;

const int S_IREAD = 256;

const int S_IRGRP = 32;

const int S_IROTH = 4;

const int S_IRUSR = 256;

const int S_IRWXG = 56;

const int S_IRWXO = 7;

const int S_IRWXU = 448;

const int S_ISGID = 1024;

const int S_ISUID = 2048;

const int S_ISVTX = 512;

const int S_IWGRP = 16;

const int S_IWOTH = 2;

const int S_IWRITE = 128;

const int S_IWUSR = 128;

const int S_IXGRP = 8;

const int S_IXOTH = 1;

const int S_IXUSR = 64;

const int TCFLSH = 21515;

const int TCGETA = 21509;

const int TCGETS = 21505;

const int TCGETX = 21554;

const int TCSBRK = 21513;

const int TCSBRKP = 21541;

const int TCSETA = 21510;

const int TCSETAF = 21512;

const int TCSETAW = 21511;

const int TCSETS = 21506;

const int TCSETSF = 21508;

const int TCSETSW = 21507;

const int TCSETX = 21555;

const int TCSETXF = 21556;

const int TCSETXW = 21557;

const int TCXONC = 21514;

const int TIOCCBRK = 21544;

const int TIOCCONS = 21533;

const int TIOCEXCL = 21516;

const int TIOCGDEV = 2147767346;

const int TIOCGETD = 21540;

const int TIOCGEXCL = 2147767360;

const int TIOCGICOUNT = 21597;

const int TIOCGLCKTRMIOS = 21590;

const int TIOCGPGRP = 21519;

const int TIOCGPKT = 2147767352;

const int TIOCGPTLCK = 2147767353;

const int TIOCGPTN = 2147767344;

const int TIOCGPTPEER = 21569;

const int TIOCGRS485 = 21550;

const int TIOCGSERIAL = 21534;

const int TIOCGSID = 21545;

const int TIOCGSOFTCAR = 21529;

const int TIOCGWINSZ = 21523;

const int TIOCINQ = 21531;

const int TIOCLINUX = 21532;

const int TIOCMBIC = 21527;

const int TIOCMBIS = 21526;

const int TIOCMGET = 21525;

const int TIOCMIWAIT = 21596;

const int TIOCMSET = 21528;

const int TIOCM_CAR = 64;

const int TIOCM_CD = 64;

const int TIOCM_CTS = 32;

const int TIOCM_DSR = 256;

const int TIOCM_DTR = 2;

const int TIOCM_LE = 1;

const int TIOCM_RI = 128;

const int TIOCM_RNG = 128;

const int TIOCM_RTS = 4;

const int TIOCM_SR = 16;

const int TIOCM_ST = 8;

const int TIOCNOTTY = 21538;

const int TIOCNXCL = 21517;

const int TIOCOUTQ = 21521;

const int TIOCPKT = 21536;

const int TIOCPKT_DATA = 0;

const int TIOCPKT_DOSTOP = 32;

const int TIOCPKT_FLUSHREAD = 1;

const int TIOCPKT_FLUSHWRITE = 2;

const int TIOCPKT_IOCTL = 64;

const int TIOCPKT_NOSTOP = 16;

const int TIOCPKT_START = 8;

const int TIOCPKT_STOP = 4;

const int TIOCSBRK = 21543;

const int TIOCSCTTY = 21518;

const int TIOCSERCONFIG = 21587;

const int TIOCSERGETLSR = 21593;

const int TIOCSERGETMULTI = 21594;

const int TIOCSERGSTRUCT = 21592;

const int TIOCSERGWILD = 21588;

const int TIOCSERSETMULTI = 21595;

const int TIOCSERSWILD = 21589;

const int TIOCSER_TEMT = 1;

const int TIOCSETD = 21539;

const int TIOCSIG = 1074025526;

const int TIOCSLCKTRMIOS = 21591;

const int TIOCSPGRP = 21520;

const int TIOCSPTLCK = 1074025521;

const int TIOCSRS485 = 21551;

const int TIOCSSERIAL = 21535;

const int TIOCSSOFTCAR = 21530;

const int TIOCSTI = 21522;

const int TIOCSWINSZ = 21524;

const int TIOCVHANGUP = 21559;

const int USER_PROCESS = 7;

const int UTIME_NOW = 1073741823;

const int UTIME_OMIT = 1073741822;

const String UTMP_FILE = '/var/run/utmp';

const String UTMP_FILENAME = '/var/run/utmp';

const int UTSNAME_DOMAIN_LENGTH = 65;

const int UTSNAME_LENGTH = 65;

const int UTSNAME_MACHINE_LENGTH = 65;

const int UTSNAME_NODENAME_LENGTH = 65;

const int UTSNAME_RELEASE_LENGTH = 65;

const int UTSNAME_SYSNAME_LENGTH = 65;

const int UTSNAME_VERSION_LENGTH = 65;

const int UT_HOSTSIZE = 256;

const int UT_LINESIZE = 32;

const int UT_NAMESIZE = 32;

const int UT_UNKNOWN = 0;

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.Int()
  external int tv_sec;

  @ffi.Int()
  external int tv_usec;
}

const int WCONTINUED = 8;

const int WEXITED = 4;

const int WNOHANG = 1;

const int WNOWAIT = 16777216;

const int WRDE_APPEND = 2;

const int WRDE_BADCHAR = 2;

const int WRDE_BADVAL = 3;

const int WRDE_CMDSUB = 4;

const int WRDE_DOOFFS = 1;

const int WRDE_NOCMD = 4;

const int WRDE_NOSPACE = 1;

const int WRDE_REUSE = 8;

const int WRDE_SHOWERR = 16;

const int WRDE_SYNTAX = 5;

const int WRDE_UNDEF = 32;

const int WSTOPPED = 2;

const String WTMP_FILE = '/var/log/wtmp';

const String WTMP_FILENAME = '/var/log/wtmp';

const int WUNTRACED = 2;

const int W_OK = 2;

const int X_OK = 1;

final class __exit_status extends ffi.Struct {
  @ffi.Short()
  external int __e_termination;

  @ffi.Short()
  external int __e_exit;
}

final class flock_t extends ffi.Struct {
  @ffi.Short()
  external int l_type;

  @ffi.Short()
  external int l_whence;

  @ffi.Long()
  external int l_start;

  @ffi.Long()
  external int l_len;

  @ffi.Int()
  external int l_pid;
}

final class glob_t extends ffi.Struct {
  @ffi.UnsignedLong()
  external int gl_pathc;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> gl_pathv;

  @ffi.UnsignedLong()
  external int gl_offs;

  @ffi.Int()
  external int gl_flags;

  external ffi
      .Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>
      gl_closedir;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>)>> gl_readdir;

  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Char>)>> gl_opendir;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Void>)>>
      gl_lstat;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Void>)>>
      gl_stat;
}

final class passwd_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> pw_name;

  external ffi.Pointer<ffi.Char> pw_passwd;

  @ffi.UnsignedInt()
  external int pw_uid;

  @ffi.UnsignedInt()
  external int pw_gid;

  external ffi.Pointer<ffi.Char> pw_gecos;

  external ffi.Pointer<ffi.Char> pw_dir;

  external ffi.Pointer<ffi.Char> pw_shell;
}

final class stat_t extends ffi.Struct {
  @ffi.UnsignedLong()
  external int st_dev;

  @ffi.UnsignedLong()
  external int st_ino;

  @ffi.UnsignedLong()
  external int st_nlink;

  @ffi.UnsignedInt()
  external int st_mode;

  @ffi.UnsignedInt()
  external int st_uid;

  @ffi.UnsignedInt()
  external int st_gid;

  @ffi.Int()
  external int __pad0;

  @ffi.UnsignedLong()
  external int st_rdev;

  @ffi.Long()
  external int st_size;

  @ffi.Long()
  external int st_blksize;

  @ffi.Long()
  external int st_blocks;

  external timespec_t st_atim;

  external timespec_t st_mtim;

  external timespec_t st_ctim;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Long> __glibc_reserved;
}

final class timespec_t extends ffi.Struct {
  @ffi.Long()
  external int tv_sec;

  @ffi.Long()
  external int tv_nsec;
}

final class utmpx_t extends ffi.Struct {
  @ffi.Short()
  external int ut_type;

  @ffi.Int()
  external int ut_pid;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> ut_line;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> ut_id;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> ut_user;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> ut_host;

  external __exit_status ut_exit;

  @ffi.Int()
  external int ut_session;

  external UnnamedStruct1 ut_tv;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Int> ut_addr_v6;

  @ffi.Array.multi([20])
  external ffi.Array<ffi.Char> __glibc_reserved;
}

final class utsname_t extends ffi.Struct {
  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> sysname;

  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> nodename;

  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> release;

  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> version;

  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> machine;

  @ffi.Array.multi([65])
  external ffi.Array<ffi.Char> __domainname;
}
